### ISSUE TITLE
FEATURE REQUEST: applying threads concept

### ISSUE THREAD

**Issue by vanetreg** [sauravjoshi23/ai#2]
I find your work very promising!
Reading your post of "Enhancing RAG with Decision-Making Agents and Neo4j Vector and Graph Chain Tools Using LangChain Templates and LangServe", especially the memory section, that's not totally clear for me, and if I'm not mistaken,
memory doesn't work on threads level ( using "threads" I mean the same concept as in OpenAI's Assistant API or in custom GPTs ).
This template is very valuable even in this form, but pls. consider my request.

**Comment by sauravjoshi23** [comment]
Thanks for pointing this out @vanetreg. You can read more about the future work in my [blog](https://medium.com/@sauravjoshi23/enhancing-rag-with-decision-making-agents-and-neo4j-graph-chain-tools-using-langchain-templates-and-0ee7d1185e48) post as I implicitly highlight the same issue. I am working on integrating the memory module into the solution. Until then, if you have figured out how to solve it, would love to integrate it via a PR
